In [1]:
# Importamos las librerías necesarias

import pandas as pd
import numpy as numpy

pd.set_option("display.max_columns", None)

import seaborn as sns
import matplotlib.pyplot as plt

Fase 1: Exploración y Limpieza
1. Exploración Inicial

In [35]:
df_clientes_vuelos = pd.read_csv("data/Customer_Flight_Activity.csv")
df_clientes_perfil = pd.read_csv("data/Customer_Loyalty_History.csv")

In [40]:
# Funcion para exploración básica

def exploracion_basica(df, nombre="Dataframe"):
    print(f"\n Exploración de: {nombre}")
    print("\n .head, datos primeros")
    display(df.head(2))
    print("=" * 100)
    print("\n .tail, datos finales")
    display(df.tail(2))
    print("=" * 100)
    print("\n .sample,datos aleatorios")
    display(df.sample(2))
    print("=" * 100)
    print("\n Información:")
    print(df.info())
    print("=" * 100)
    print(f"El dataframe tiene {df.shape[0]} filas y {df.shape[1]} columnas")

In [41]:
exploracion_basica(df_clientes_vuelos, "Clientes Vuelos")
exploracion_basica(df_clientes_perfil, "Clientes Perfil")

 Exploración de: Clientes Vuelos

 .head, datos primeros

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0

====================================================================================================

 .tail, datos finales

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
405622,999982,2018,12,0,0,0,0,0.0,0,0
405623,999986,2018,12,0,0,0,0,0.0,0,0

====================================================================================================

 .sample,datos aleatorios

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
349860,729293,2018,9,10,5,15,1185,118.0,0,0
240424,623154,2018,12,0,0,0,0,0.0,0,0

====================================================================================================

 Información:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB
None
====================================================================================================
El dataframe tiene 405624 filas y 10 columnas

 Exploración de: Clientes Perfil

 .head, datos primeros

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN

====================================================================================================

 .tail, datos finales

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
16735,906428,Canada,Yukon,Whitehorse,Y2K 6R0,Male,Bachelor,-57297.0,Married,Star,10018.66,2018 Promotion,2018,4,NaN,NaN
16736,652627,Canada,Manitoba,Winnipeg,R2C 0M5,Female,Bachelor,75049.0,Married,Star,83325.38,Standard,2015,12,2016.0,8.0

====================================================================================================

 .sample,datos aleatorios

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
3541,478284,Canada,British Columbia,Vancouver,V6E 3D9,Male,Bachelor,62244.0,Married,Aurora,14333.92,Standard,2016,10,2017.0,6.0
6448,430413,Canada,British Columbia,Vancouver,V6E 3D9,Male,Bachelor,62298.0,Married,Nova,5176.73,Standard,2015,12,NaN,NaN

====================================================================================================

 Información:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  object
 2   Province            16737 non-null  object
 3   City                16737 non-null  object
 4   Postal Code         16737 non-null  object
 5   Gender              16737 non-null  object
 6   Education           16737 non-null  object
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  object
 9   Loyalty Card        16737 non-null  object
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  object
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), object(9)
memory usage: 2.0+ MB
None
====================================================================================================
El dataframe tiene 16737 filas y 16 columnas

##  Conclusiones del análisis de datos

Según los datos obtenidos, podemos extraer las siguientes conclusiones:

- Las columnas de ambos archivos presentan una estructura homogénea en cuanto a nomenclatura, siguiendo el formato de primera letra en mayúscula y el resto en minúsculas.

- Se ha detectado que en la columna **Enrollment Type** existen valores que combinan el año y la categoría de forma repetida, por lo que sería necesario realizar una limpieza o transformación de estos datos en el DataFrame de **df_clientes_perfil**.

- El DataFrame **df_clientes_vuelos** contiene un mayor número de filas que **df_clientes_perfil**, lo cual es coherente, ya que un mismo cliente puede realizar múltiples vuelos.
La Relación entre tablas es 1:N y se conectan por Loyalty Number.

###  df_clientes_vuelos

- No se han identificado valores nulos.

###  df_clientes_perfil

- Se han identificado valores nulos en:
  - **Salary**: 4.238 nulos  
  - **Cancellation Year**: 14.670 nulos  
  - **Cancellation Month**: 14.670 nulos
  - En Cancellation Year y Month hay muchos nulos, muchos clientes que no han cancelado

- Sería recomendable cambiar el tipo de dato de las columnas:
  - **Cancellation Year** → entero  
  - **Cancellation Month** → entero 
  - Ya que no tiene sentido tenerlos como float siendo enteros el año y mes. Tener en cuenta que tiene nulos a la hora de pasarlo a entero, ya que panda los convierte a float.
  - Los valores nulos en Cancellation Year y Cancellation Month probablemente indican que el cliente no ha cancelado. Podemos dejarlos en nulo y con la función Int64 pasar el tipo de dato a entero y añadir una columna de Cancelled que nos indique si ha cancelado o no con algun valor ejemplo 0/1 o si/no.
  - Pero tambien tenemos que fijarnos en que los dos valores de las columnas de year y month esten completas para que nos identifique si hay algun error en esos datos y se cumpla la condición.

In [51]:
df_clientes_perfil[
    df_clientes_perfil["Cancellation Year"].notnull() & 
    df_clientes_perfil["Cancellation Month"].isnull()
]

Empty DataFrame
Columns: [Loyalty Number, Country, Province, City, Postal Code, Gender, Education, Salary, Marital Status, Loyalty Card, CLV, Enrollment Type, Enrollment Year, Enrollment Month, Cancellation Year, Cancellation Month]
Index: []

In [52]:
df_clientes_perfil[
    df_clientes_perfil["Cancellation Year"].isnull() & 
    df_clientes_perfil["Cancellation Month"].notnull()
]

Empty DataFrame
Columns: [Loyalty Number, Country, Province, City, Postal Code, Gender, Education, Salary, Marital Status, Loyalty Card, CLV, Enrollment Type, Enrollment Year, Enrollment Month, Cancellation Year, Cancellation Month]
Index: []

In [53]:
df_clientes_perfil["Cancelled"] = (
    df_clientes_perfil["Cancellation Year"].notnull() |
    df_clientes_perfil["Cancellation Month"].notnull()
).astype(int)

In [54]:
df_clientes_perfil.head(5)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month,Cancelled
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN,0
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN,0
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0,1
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN,0
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN,0